services:
  ev-charger-all-in-one:
    build: .
    container_name: ev-charger-all-in-one
    restart: unless-stopped
    environment:
      RUNNER_NAME: home-pc-runner
      RUNNER_SCOPE: repo
      REPO_URL: https://github.com/Murianwind/ev_charger_map
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      LABELS: self-hosted,home-pc
      RUNNER_WORKDIR: /tmp/runner/work
    volumes:
      - runner-work:/tmp/runner/work

volumes:
  runner-work:
